---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: harbor.158.160.5.137.nip.io/dotnet-app:latest 
        ports:
        - containerPort: 5000
        imagePullSecrets:
        - name: harbor-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  namespace: apps
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dotnet-app-ingress
  namespace: apps
  annotations:
    kubernetes.io/tls-acme: "false"
spec:
  rules:
  -
    host: dotnet-app.158.160.5.137.nip.io
    http:
      paths: 
      -
        path: /
        pathType: Prefix
        backend:
          service:
            name: dotnet-app
            port:
              number: 5000