apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: apps
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuMTU4LjE2MC41LjEzNy5uaXAuaW8iOnsidXNlcm5hbWUiOiJkZXBsb3ktdXNlciIsInBhc3N3b3JkIjoiMTAyMDMwUXEiLCJhdXRoIjoiWkdWd2JHOTVMWFZ6WlhJNk1UQXlNRE13VVhFPSJ9fX0=
