apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: harbor.158.160.26.84.nip.io/python-app:latest  
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: apps
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
  type: ClusterIP
---
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: python-app-ingress
  namespace: apps
  annotations:
    kubernetes.io/tls-acme: "false"
spec:
  rules:
  -
    host: python-app.158.160.5.137.nip.io
    http:
      paths: 
      -
        path: /
        pathType: Prefix
        backend:
          service:
            name: python-app
            port:
              number: 8080