apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: harbor.158.160.26.84.nip.io/go-app:latest  
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: apps
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080
  type: ClusterIP 
---
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: go-app-ingress
  namespace: apps
  annotations:
    kubernetes.io/tls-acme: "false"
spec:
  rules:
  -
    host: go-app.158.160.5.137.nip.io
    http:
      paths: 
      -
        path: /
        pathType: Prefix
        backend:
          service:
            name: go-app
            port:
              number: 8080